<div class="row">

	<div class="col-sm-12">

		<h1>Lista de categorías</h1>

        <div class="table-responsive">

			<table border="1" class="table table-striped table-dark">

				<tr>
					<th>ID</th>
					<th>Nombre</th>
                    <th><p>Acción<p/></th>
				</tr>

                <?php foreach ($this->categorias as $categoria): ?>

                <tr>

                    <td><?php echo $categoria["id"]; ?></td>

                    <td><?php echo $categoria["nombre"]; ?></td>

                    <td>
                    
                        <a href="<?php echo APP_URL."categorias/editar/".$tarea["tareas"]["id"]; ?>">
							
							<button type="button" class="btn btn-light">Editar</button>

						</a>

                        |

                        <a href="<?php echo APP_URL."categorias/eliminar/".$tarea["tareas"]["id"]; ?>">
							
							<button type="button" class="btn btn-danger">Eliminar</button>

						</a>
                    
                    
                    
                    </td>

                </tr>

                <?php endforeach; ?>

			</table>

		</div>

    </div>

</div>